// Generates 2 years of daily color assignments.
// Run: node supabase/seed.js
// Output is written to supabase/seeds/colors.sql

const fs = require('fs');
const path = require('path');

const PALETTE = [
  { name: 'Coral',        hex: '#E8735A' },
  { name: 'Forest Green', hex: '#3A7D44' },
  { name: 'Sky Blue',     hex: '#6DB5E8' },
  { name: 'Golden',       hex: '#F5C842' },
  { name: 'Lavender',     hex: '#A78BFA' },
  { name: 'Terracotta',   hex: '#C1673E' },
  { name: 'Mint',         hex: '#4ECDC4' },
  { name: 'Rose',         hex: '#E879A0' },
  { name: 'Slate',        hex: '#64748B' },
  { name: 'Amber',        hex: '#F59E0B' },
  { name: 'Indigo',       hex: '#6366F1' },
  { name: 'Sage',         hex: '#84A98C' },
];

// Seeded shuffle so the sequence is reproducible
function seededShuffle(arr, seed) {
  const a = [...arr];
  let s = seed;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Build a long non-repeating sequence by shuffling each "round" differently
function buildSequence(length) {
  const result = [];
  let round = 0;
  while (result.length < length) {
    result.push(...seededShuffle(PALETTE, round * 999983));
    round++;
  }
  return result.slice(0, length);
}

const START = new Date('2025-01-01');
const DAYS = 365 * 3; // 3 years — plenty of runway
const sequence = buildSequence(DAYS);

const rows = [];
for (let i = 0; i < DAYS; i++) {
  const d = new Date(START);
  d.setDate(START.getDate() + i);
  const date = d.toISOString().slice(0, 10);
  const { name, hex } = sequence[i];
  rows.push(`  ('${date}', '${name}', '${hex}')`);
}

const sql = [
  '-- Mosaic color seed — 3 years of daily assignments',
  '-- Generated by supabase/seed.js',
  '',
  'INSERT INTO colors (date, name, hex) VALUES',
  rows.join(',\n'),
  'ON CONFLICT (date) DO NOTHING;',
  '',
].join('\n');

const outDir = path.join(__dirname, 'seeds');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);
fs.writeFileSync(path.join(outDir, 'colors.sql'), sql);

console.log(`✓ Generated ${DAYS} days of colors → supabase/seeds/colors.sql`);
